from __future__ import annotations

from typing import List

import numpy as np
import numpy.typing as npt

CONTINUOUS: int
INTEGER: int
SEMI_CONTINUOUS: int
SEMI_INTEGER: int


class SparseMatrix:
    @property
    def start(self) -> npt.NDArray[np.uint32]: ...
    @property
    def index(self) -> npt.NDArray[np.uint32]: ...
    @property
    def value(self) -> npt.NDArray[np.float64]: ...


class Model:
    @property
    def name(self) -> str: ...
    @property
    def num_row(self) -> int: ...
    @property
    def num_col(self) -> int: ...
    @property
    def obj_sense_minimize(self) -> bool: ...
    @property
    def obj_offset(self) -> float: ...
    @property
    def objective_name(self) -> str: ...
    @property
    def col_cost(self) -> npt.NDArray[np.float64]: ...
    @property
    def col_lower(self) -> npt.NDArray[np.float64]: ...
    @property
    def col_upper(self) -> npt.NDArray[np.float64]: ...
    @property
    def row_lower(self) -> npt.NDArray[np.float64]: ...
    @property
    def row_upper(self) -> npt.NDArray[np.float64]: ...
    @property
    def col_integrality(self) -> npt.NDArray[np.uint8]: ...
    @property
    def a_matrix(self) -> SparseMatrix: ...
    @property
    def col_names(self) -> List[str]: ...
    @property
    def row_names(self) -> List[str]: ...


def parse_file(path: str) -> Model: ...
def parse_str(content: str) -> Model: ...
def write_file(model: Model, path: str) -> None: ...
def write_str(model: Model) -> str: ...
